#!/usr/bin/env python3
"""
Sicang5 词库生产脚本 (单字版)
1. 优先级：简码(z/1/2/3) > 单字四码。
2. 词组功能：逻辑已在 SPEC 中定义，脚本中暂不启用词组生成。
"""

import sys
from pathlib import Path

# 导入通用工具
sys.path.append(str(Path(__file__).resolve().parent))
from cangjie_builder import (
    parse_cangjie_dict,
    parse_frequency_file,
    is_han_char,
    project_code,
    REPO_ROOT
)

def main():
    source_dict = REPO_ROOT / "cangjie5/cangjie5.dict.yaml"
    freq_file = REPO_ROOT / "sancang5/essay-zh-hans.txt"
    output_path = REPO_ROOT / "sicang5/sicang5.dict.yaml"
    
    shortcuts = {
        1: REPO_ROOT / "sicang5/sicang5_1.txt",
        2: REPO_ROOT / "sicang5/sicang5_2.txt",
        3: REPO_ROOT / "sicang5/sicang5_3.txt",
        'z': REPO_ROOT / "sicang5/sicang5_z.txt"
    }

    print("正在解析原始仓颉编码...")
    raw_entries = parse_cangjie_dict(source_dict)
    char_full_codes = {}
    for e in raw_entries:
        if is_han_char(e.text) and not (e.code.startswith('z') or e.code.startswith('x')):
            if e.text not in char_full_codes or len(e.code) < len(char_full_codes[e.text]):
                char_full_codes[e.text] = e.code

    final_table = [] 
    used_text_code = set()

    # 1. 加载简码 (最高优先级)
    print("正在加载简码规则...")
    def load_shortcut(path, base_weight):
        if not path.exists(): return
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"): continue
                parts = line.split("\t")
                if len(parts) == 2:
                    char, code = parts[0], parts[1]
                    final_table.append((char, code, base_weight))
                    used_text_code.add((char, code))

    load_shortcut(shortcuts['z'], 1000000)
    load_shortcut(shortcuts[1], 900000)
    load_shortcut(shortcuts[2], 800000)
    load_shortcut(shortcuts[3], 700000)

    # 2. 生成单字四码
    print("正在生成单字四码...")
    char_freqs, _ = parse_frequency_file(freq_file)
    for char, full_code in char_full_codes.items():
        # 单字规则：取全码投影（前三码+末码，若不满四码则为原码）
        code4 = project_code(full_code, 4)
        if (char, code4) not in used_text_code:
            final_table.append((char, code4, char_freqs.get(char, 0)))
            used_text_code.add((char, code4))

    print(f"正在写入 {output_path}...")
    # 排序：编码升序，同码按权重降序
    final_table.sort(key=lambda x: (x[1], -x[2]))
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("# encoding: utf-8\n")
        f.write("# Sicang5 Fixed-length Dictionary\n")
        f.write("# Generated by scripts/cangjie/gen_sicang5.py\n")
        f.write("---\nname: sicang5\nversion: '1.0'\nsort: by_weight\n...\n\n")
        for text, code, _ in final_table:
            f.write(f"{text}\t{code}\n")

    print(f"完成！已生成全量单字定长词库。输出：{output_path}")

if __name__ == "__main__":
    main()
